export let answers = [
    "A loving person will be coming into your life",
    "A dubious friend may be an enemy in camouflage",
    "A faithful friend is a strong defense",
    "A fresh start will put you on your way",
    "A friend asks for your time not your money",
    "A friend is a present you give yourself",
    "A golden opportunity will soon arrive",
    "A good time to finish up old tasks",
    "A hunch is trying to tell you something",
    "A lifetime friend shall soon be made",
    "A lifetime of happiness lies ahead of you",
    "New year = New perspective",
    "A person is never to old to learn",
    "A pleasant surprise is waiting for you",
    "A smile is your personal welcome mat",
    "A smooth long journey! Great expectations",
    "A soft voice may be awfully persuasive",
    "A rich life contains love and art in abundance",
    "Adventure can be real happiness",
    "Advice, when most needed, is least heeded",
    "All the effort you are making will pay off",
    "All will go well with your new project",
    "All your hard work will soon pay off",
    "Allow compassion to guide your decisions",
    "An romance might begin to take on the appearance",
    "An important person will offer you support",
    "An inch of time is an inch of gold",
    "At the touch of love, everyone becomes a poet",
    "Be careful or you could fall for some tricks today",
    "Beauty in its various forms appeals to you",
    "Believe in yourself and others will too",
    "Believe it can be done",
    "Better ask twice than lose yourself once",
    "Bide your time, for success is near",
    "Carve your name on your heart and not on marble",
    "Change is happening in your life, so go with the flow!",
    "Competence like yours is underrated",
    "Congratulations! You are on your way",
    "Could I get some directions to your heart?",
    "Courtesy begins in the home",
    "Courtesy is contagious",
    "Curiosity kills boredom. Nothing can kill curiosity",
    "Determination is what you need now",
    "Disbelief destroys the magic",
    "Distance yourself from the vain",
    "Do not be intimidated by the eloquence of others",
    "Do not let ambitions overshadow small success",
    "Do not make extra work for yourself",
    "Do not underestimate yourself",
    "Every wrong attempt is another step forward",
    "Don’t be discouraged",
    "Don’t confuse recklessness with confidence",
    "Don’t just spend time. Invest it",
    "Don’t just think, act!",
    "Work calmly and silently",
    "Don’t let the past choke your existence",
    "Don’t let your limitations overshadow your talents",
    "Don’t worry; prosperity will knock on your door soon",
    "Education is the ability to meet life’s situations",
    "Embrace this love relationship you have!",
    "Emulate what you admire in your parents",
    "Emulate what you respect in your friends",
    "Every flower blooms in its own sweet time",
    "Every wise man started out by asking questions",
    "Everyday in your life is a special occasion",
    "Everywhere you go, friendly faces will greet you",
    "Expect much of yourself and little of others",
    "Failure is the chance to do better next time",
    "Failure is the path of lease persistence",
    "Fear and desire, two sides of the same coin",
    "Fearless courage is the foundation of victory",
    "Hate is conquered by love",
    "Fortune Not Found: Abort, Retry, Ignore?",
    "From listening comes wisdom",
    "Your kindness will lead you to success",
    "Get your mind set, confidence will lead you on",
    "Go for the gold today!",
    "Go take a rest, you deserve it",
    "Good news will be brought to you by email",
    "Good news will come to you by email",
    "Good to begin well, better to end well",
    "Face life with a smile and a wink ;)",
    "Happiness will bring you good luck",
    "Look! ☘ A four leaf clover. Lucky you!",
    "Happy life is just in front of you",
    "Hard words break no bones...",
    "Have a beautiful day",
    "He who knows he has enough is rich",
    "He who knows himself is enlightened",
    "Look behind you, a three headed monkey! - GT",
    "I learn by going where I have to go",
    "If certainty were truth, we would never be wrong",
    "If you continually give, you will continually have",
    "Imagination rules the world",
    "In order to take, one must first give",
    "In the end all things will be known",
    "In this weird world, It’s better to be merry than wise",
    "It could be better, but its good enough",
    "It is better to deal with problems before they arise",
    "Stand up for what is right, however unpopular it seems",
    "It is worth reviewing some old lessons",
    "It takes courage to admit fault",
    "It’s time to get moving",
    "This is the sign you've been looking for",
    "Let the world be filled with tranquility and goodwill",
    "Some things are meant to be",
    "Listen not to vain words of empty tongue",
    "Listen to everyone. Ideas come from everywhere",
    "Focus on your commitment and results will come",
    "Long life is in store for you",
    "Love is a warm fire to keep the soul warm",
    "Love is like sweet medicine, good to the last drop",
    "Love lights up the world",
    "Love truth, but pardon error",
    "Man is born to live and not prepared to live",
    "Many will travel to hear you speak",
    "Meditation with an old enemy is advised",
    "Miles are covered one step at a time",
    "Nature, time & patience are the 3 great physicians",
    "Never fear my friend!",
    "The end of something marks the start of something new",
    "New ideas could be profitable",
    "New people will bring you new realizations",
    "No one can walk backwards into the future",
    "Now is a good time to buy stock",
    "Go ahead and pursue that love interest!",
    "Now is the time to try something new",
    "Observe all humans, but most of all yourself",
    "Look for the positive side",
    "Others can help you now",
    "Good vibes find their way to your doorstep this year",
    "People find it difficult to resist you",
    "Perhaps you’ve been focusing too much on saving",
    "Pick battles big enough to matter",
    "Place special emphasis on old friendship",
    "Practice makes perfect",
    "Protective measures will prevent costly disasters",
    "Put your mind into planning today",
    "Remember the birthday but never the age",
    "Remember to share good fortune with your friends",
    "Resting well is as important as working hard",
    "Romance moves you in a new direction",
    "Savor your freedom – it is precious",
    "Say hello to others. You will have a happier day",
    "Self-knowledge is a life long process",
    "Share your joys and sorrows with your family",
    "Small confidences mark the onset of a friendship",
    "Someone you care about seeks reconciliation",
    "Soon life will become more interesting",
    "Stand tall. Don’t look down upon yourself",
    "Stop searching, happiness is just next to you",
    "Strong reasons make strong actions",
    "Success is a journey, not a destination",
    "Success is failure turned inside out",
    "Swimming is easy. Stay floating is hard",
    "Take the high road",
    "The best prediction of future is the past",
    "It is coming. Be ready",
    "The harder you work, the luckier you get",
    "The saints are the sinners who keep on trying",
    "The secret to good friends is no secret to you",
    "Trust your intuitions",
    "The sure way to predict the future is to invent it",
    "The truly generous share, even with the undeserving",
    "The weather is wonderful",
    "There is a time for caution, but not for fear",
    "There is no wisdom greater than kindness",
    "Things don’t just happen; they happen just",
    "Those who care will make the effort",
    "Surprises await you!",
    "Time is precious but truth is more precious than time",
    "To know oneself, one should assert oneself",
    "Tonight you will be blinded by passion",
    "Use your eloquence where it will do the most good",
    "We first make our habits, and then our habits make us",
    "Welcome change",
    "'Welcome' is a powerful word",
    "Well done is better than well said",
    "What’s hidden in an empty box?",
    "What’s that in your eye? Oh… it’s a sparkle",
    "What’s yours in mine, and what’s mine is mine",
    "When your heart is pure, your mind is clear",
    "Wish you happiness",
    "With age comes wisdom",
    "You adventure could lead to happiness",
    "You always bring others happiness",
    "You are a person of another time",
    "You are a talented storyteller",
    "You are admired by everyone for your talent",
    "You are almost there",
    "You are busy, but you are happy",
    "You are going to have some new clothes",
    "You are in good hands this evening",
    "You are modest and courteous",
    "Say yes!",
    "You are solid and dependable",
    "You are talented in many ways",
    "You are the master of every situation",
    "You are working hard",
    "You can keep a secret",
    "You can see a lot just by looking",
    "You desire recognition and you will find it",
    "You have a yearning for perfection",
    "You've an unusual magnet for success, use it properly",
    "You have exceeded what was expected",
    "You have had a good start. Work harder!",
    "You have the power to write your own fortune",
    "You have yearning for perfection",
    "You know where you are going and how to get there",
    "You look pretty",
    "You love challenge",
    "You can tackle the most difficult problems",
    "You never know who you touch",
    "You only treasure what you lost",
    "You should be able to undertake anything",
    "You should pay for this check. Be generous",
    "Have fun with others and to enjoy your solitude",
    "You will always be surrounded by true friends",
    "You will be blessed with longevity",
    "You will be pleasantly surprised tonight",
    "You will be successful in your work",
    "You will be traveling soon",
    "You will become more and more wealthy",
    "You will enjoy good health",
    "You will make change for the better",
    "You'll take a chance in something in near future",
    "You will travel far and wide",
    "Your abilities are unparalleled",
    "Your ability is appreciated",
    "Your ability to juggle many tasks will take you far",
    "Your biggest virtue is your modesty",
    "Your difficulties will strengthen you",
    "Your dreams are never silly",
    "Your dreams are worth everything",
    "Your family is young, gifted and attractive",
    "Your first love has never forgotten you",
    "Your goal will be reached very soon",
    "Your happiness is before you, not behind! Cherish it",
    "Your hard work will payoff today",
    "Your home is the center of great love",
    "Your ideals are well within your reach",
    "Your leadership qualities will be tested and proven",
    "Your life will be happy and peaceful",
    "Your life will get more and more exciting",
    "Your love life will be happy and harmonious",
    "Your mind is creative, original and alert",
    "Your mind is your greatest asset",
    "Your moods signal a period of change",
    "Your quick wits will get you out of a tough situation",
    "Your reputation is your wealth",
    "Your success will astonish everyone",
    "Your talents will be recognized and suitably rewarded",
    "An old love will come back to you",
    "You have a secret admirer",
    "Do what you love. The rest will fall into place",
    "Follow what you love and see what turns up",
    "You should def go for it",
    "Enter unknown territory",
    "Make self care a non-negotiable",
    "Focus on the magic of things; yourself",
    "Change comes with embracing the future",
    "To be found, stop hiding",
    "Some things are just too heavy to haul around",
    "Your road to glory will be rocky, but fulfilling",
    "Nothing is impossible to a willing heart",
    "Don’t worry about $ - the best things in life are free",
    "Don’t pursue happiness – create it",
    "All things are difficult before they are easy",
    "He who throws mud loses ground",
    "Success lies in the hands of those who wants it",
    "Big journeys begin with a single step",
    "Never forget that a half truth is a whole lie",
    "Serious trouble will bypass you",
    "The greatest risk is not taking one",
    "Love can last a lifetime, if you want it to",
    "Let the deeds speak",
    "Express yourself. Don't hold back!",
    "Nothing seems impossible to you",
    "Your dearest wish will come true",
    "A merry heart does good like a medicine",
    "Whenever possible, keep it simple",
    "Unleash your life force",
    "Make a wise choice everyday",
    "True wisdom is found in happiness",
    "A feeling is an idea with roots",
    "Good things take time",
    "Let your fantasies unwind...",
    "Failure is the mother of all success",
    "Seize every second of your life and savor it",
    "Things are never quite the way they seem",
    "Tell them before it's too late...",
    "Forgive your enemies, but never forget them",
    "Your fortune is as sweet as a cookie",
    "About time I got out of that cookie",
    "Love will lead the way",
    "Soon, a visitor shall delight you",
    "Plan your work and work your plan",
    "Love or money, or neither?",
    "Be prepared for extra energy",
    "Enjoy yourself while you can",
    "Never cut what you can untie",
    "Use your instincts now",
    "Warning, do not eat your fortune",
    "Oops... Wrong cookie",
    "Fortune smiles upon you today",
    "Use your talents. That's what they are intended for",
    "See the light at the end of the tunnel",
    "Stop procrastinating",
    "May you have great luck",
    "Accept what comes to you each day",
    "In human endeavor, chance favors the prepared mind",
    "Do not upset the penguin today",
    "Treasure what you have",
    "Live each day well and wisely",
    "Keep your plans secret for now",
    "Take it easy",
    "The universe is guiding your life",
    "Listen to yourself more often",
    "He who seeks will find",
    "Face facts with dignity",
    "Good beginning is half done",
    "Don't just spend time, invest it",
    "Never quit!",
    "Be a generous friend and a fair enemy",
    "Smile. Tomorrow is another day",
    "Never do anything halfway",
    "Ignore previous cookie",
    "I cannot help you, for I am just a cookie ☺",
    "You will soon discover your hidden talent",
    "Keep your eye out for someone special",
    "A new voyage will fill your life with untold memories",
    "Land is always on the mind of a flying bird",
    "People are naturally attracted to you",
    "Discover the power within yourself",
    "Never regret anything that made you smile",
    "New opportunities will be presented to you",
    "You cannot direct the wind, so adjust the sails",

];

